version: '2.0'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DATABASE: healthcare
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

